title: "Kata_web by changcheng967"
description: "Official Kata_web releases page"

collections:
  releases:
    output: true
    permalink: /release/:name/

markdown: kramdown
highlighter: rouge

baseurl: ""

plugins:
  - jekyll-feed
