name: Build & Deploy Release Website

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all releases info
        id: fetch_releases
        uses: past-due/fetch-release-info@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_release_index: true

      - name: Write release data
        run: |
          mkdir -p _data
          echo "${{ steps.fetch_releases.outputs.index }}" > _data/releases.json

      # Only include below steps if you have a Gemfile / use Jekyll
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build --destination _site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
