# .github/workflows/release-site.yml

name: Build & Deploy Static Releases Page

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch releases JSON
      run: |
        curl -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/changcheng967/Kata_web/releases > releases.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .   # publish root (includes index.html + releases.json)
        # optionally set enable_jekyll, or leave it off if you want static only
        enable_jekyll: false

